export const author: string;
export const date: string;
export const icon: string;
export const info: string;
export const main: string;
export const post: string;
export const postTitle: string;
export const tag: string;
export const tagList: string;
